import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"

export default function PrivacyPolicyPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />
      <main className="flex-1 py-12 md:py-24 lg:py-32 bg-background text-foreground">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Privacy Policy</h1>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Your privacy is important to us. This policy explains how we collect, use, and protect your personal
                information.
              </p>
            </div>
            {/* Placeholder for privacy policy content */}
            <div className="w-full max-w-3xl mx-auto bg-card p-6 rounded-lg shadow-md mt-8 text-left space-y-4">
              <p>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
                information when You use the Service and tells You about Your privacy rights and how the law protects
                You.
              </p>
              <p>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
                collection and use of information in accordance with this Privacy Policy.
              </p>
              <h2 className="text-xl font-bold mt-6">Interpretation and Definitions</h2>
              <h3 className="font-semibold text-lg">Interpretation</h3>
              <p>
                The words of which the initial letter is capitalized have meanings defined under the following
                conditions. The following definitions shall have the same meaning regardless of whether they appear in
                singular or in plural.
              </p>
              <h3 className="font-semibold text-lg">Definitions</h3>
              <ul className="list-disc pl-5 space-y-1">
                <li>
                  <strong>Account</strong> means a unique account created for You to access our Service or parts of our
                  Service.
                </li>
                <li>
                  <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
                  refers to Scarves Co.
                </li>
                <li>
                  <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other
                  device by a website, containing the details of Your browsing history on that website among its many
                  uses.
                </li>
                <li>
                  <strong>Country</strong> refers to: United States
                </li>
                <li>
                  <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone
                  or a digital tablet.
                </li>
                <li>
                  <strong>Personal Data</strong> is any information that relates to an identified or identifiable
                  individual.
                </li>
                <li>
                  <strong>Service</strong> refers to the Website.
                </li>
                <li>
                  <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf
                  of the Company. It refers to third-party companies or individuals employed by the Company to
                  facilitate the Service, to provide the Service on behalf of the Company, to perform services related
                  to the Service or to assist the Company in analyzing how the Service is used.
                </li>
                <li>
                  <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
                  Service or from the Service infrastructure itself (for example, the duration of a page visit).
                </li>
                <li>
                  <strong>Website</strong> refers to Scarves Co., accessible from https://www.scarvesco.com
                </li>
                <li>
                  <strong>You</strong> means the individual accessing or using the Service, or the company, or other
                  legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </main>
      <SiteFooter />
    </div>
  )
}
